#!/usr/bin/env python3
# ================== #
"""
The script was generated by AI and may not work correctly.
I'll add this functionality to the builder later; this is a temporary solution.
"""
# ================== #
# -*- coding: utf-8 -*-
"""
Universal vendor submodule initializer & builder for Rinegine.
Smart host-aware build with interactive target/compiler selection.
Usage: python3 vendor-build.py [--target platform:arch] [--all]
"""

import os
import sys
import subprocess
import shutil
import argparse
import time
from pathlib import Path
from typing import Optional, Tuple, List, Dict
import platform as sys_platform

# ============================================================================
# Configuration
# ============================================================================

try:
    ROOT_DIR = Path(
        subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
    )
except FileNotFoundError:
    print("❌ Error: git is not installed or not in PATH")
    sys.exit(1)
except subprocess.CalledProcessError:
    print("❌ Error: Not inside a Git repository.")
    sys.exit(1)

VENDOR_DIR = ROOT_DIR / "vendor"
GLOBAL_INCLUDE_DIR = VENDOR_DIR / "include"
ANDROID_MIN_SDK = 21

ALL_SUBMODULES = [
    "vendor/src/glfw",
    "vendor/src/freetype",
    "vendor/include/stb"
]

ALL_TARGETS = [
    "linux:x86_64", "linux:x86_32", "linux:arm64-v8a", "linux:armeabi-v7a",
    "windows:x86_64", "windows:x86_32",
    "android:arm64-v8a", "android:armeabi-v7a", "android:x86_64",
]

# ============================================================================
# Utility Functions
# ============================================================================

def log_step(msg: str):
    print(f"\n{'='*65}\n {msg}\n{'='*65}")

def log_info(msg: str):
    print(f"  ℹ️  {msg}")

def log_success(msg: str):
    print(f"  ✅ {msg}")

def log_warn(msg: str):
    print(f"  ⚠️  {msg}")

def log_error(msg: str):
    print(f"  ❌ {msg}", file=sys.stderr)

def find_executable(name: str) -> Optional[Path]:
    path = shutil.which(name)
    return Path(path) if path else None

def run_cmd(cmd: List[str], cwd: Optional[Path] = None) -> bool:
    log_info(f"$ {' '.join(str(c) for c in cmd)}")
    try:
        subprocess.run(cmd, cwd=cwd, check=True)
        return True
    except subprocess.CalledProcessError:
        return False
    except FileNotFoundError:
        log_error(f"Command not found: {cmd[0]}")
        return False

def safe_rmtree(path: Path, retries: int = 3):
    if not path.exists():
        return
    for attempt in range(retries):
        try:
            shutil.rmtree(path)
            return
        except PermissionError:
            if attempt < retries - 1:
                log_warn(f"File locked, retrying... ({attempt + 1}/{retries})")
                time.sleep(1)
            else:
                log_error(f"Cannot remove {path}: files are locked")
                raise

def interactive_choice(prompt: str, options: List[str], default: int = 0) -> int:
    print(f"\n{prompt}")
    for i, opt in enumerate(options):
        marker = "➤" if i == default else " "
        print(f"  {marker} [{i+1}] {opt}")
    while True:
        choice = input(f"\nEnter number [1-{len(options)}] (default={default+1}): ").strip()
        if not choice:
            return default
        try:
            idx = int(choice) - 1
            if 0 <= idx < len(options):
                return idx
        except ValueError:
            pass
        print("Invalid input, try again.")

def interactive_multi_select(prompt: str, options: List[str], recommended: List[int]) -> List[int]:
    print(f"\n{prompt}")
    print("  (Enter comma-separated numbers, 'r' for recommended, 'a' for all, or 'q' to confirm)")
    for i, opt in enumerate(options):
        marker = "★" if i in recommended else " "
        print(f"  {marker} [{i+1}] {opt}")
    
    while True:
        choice = input(f"\nYour choice (default='r'): ").strip().lower()
        if not choice or choice == "r":
            return recommended
        if choice == "a":
            return list(range(len(options)))
        if choice == "q":
            return recommended
        try:
            selected = [int(x.strip()) - 1 for x in choice.split(",")]
            if all(0 <= i < len(options) for i in selected):
                return selected
        except ValueError:
            pass
        print("Invalid input, try again.")

# ============================================================================
# Host Capability Detection
# ============================================================================

def detect_host() -> Dict:
    host_os = sys_platform.system().lower()
    host_arch = sys_platform.machine().lower()
    
    if host_arch in ("amd64", "x86_64"): host_arch = "x86_64"
    elif host_arch in ("i686", "i386", "x86"): host_arch = "x86_32"
    elif "aarch64" in host_arch or "arm64" in host_arch: host_arch = "aarch64"
    elif "arm" in host_arch: host_arch = "arm"
    
    compilers = []
    if find_executable("clang") and find_executable("clang++"):
        compilers.append(("clang", str(find_executable("clang")), str(find_executable("clang++"))))
    if find_executable("gcc") and find_executable("g++"):
        compilers.append(("gcc", str(find_executable("gcc")), str(find_executable("g++"))))
    
    has_ndk = False
    ndk_candidates = [
        os.environ.get("ANDROID_NDK"), os.environ.get("ANDROID_NDK_HOME"),
        str(Path.home() / "Android/Sdk/ndk-bundle"),
        str(Path.home() / "AppData/Local/Android/Sdk/ndk-bundle"),
    ]
    if host_os == "darwin":
        ndk_candidates.append(str(Path.home() / "Library/Android/sdk/ndk-bundle"))
    for search_dir in [
        Path.home() / "Android/Sdk/ndk", Path.home() / "Library/Android/sdk/ndk",
        Path.home() / "AppData/Local/Android/Sdk/ndk",
    ]:
        if search_dir.is_dir():
            ndk_candidates += [str(d) for d in search_dir.iterdir() if d.is_dir()]
    
    for p in ndk_candidates:
        if p and Path(p).is_dir() and (Path(p) / "build/cmake/android.toolchain.cmake").exists():
            has_ndk = True
            break
    
    # Check for MinGW with both gcc and clang variants
    has_mingw = bool(
        find_executable("x86_64-w64-mingw32-gcc") or 
        find_executable("i686-w64-mingw32-gcc") or
        find_executable("x86_64-w64-mingw32-clang") or
        find_executable("i686-w64-mingw32-clang")
    )
    
    has_multilib = False
    if host_arch == "x86_64" and host_os == "linux":
        try:
            test_result = subprocess.run(
                ["gcc", "-m32", "-x", "c", "-c", "-", "-o", "/dev/null"],
                input=b"int main() { return 0; }",
                capture_output=True, timeout=5
            )
            has_multilib = (test_result.returncode == 0)
        except Exception:
            has_multilib = False
    
    current_android_arch = None
    if host_os == "android":
        if host_arch == "aarch64": current_android_arch = "arm64-v8a"
        elif host_arch == "arm": current_android_arch = "armeabi-v7a"
        elif host_arch == "x86_64": current_android_arch = "x86_64"
        elif host_arch == "x86_32": current_android_arch = "x86"
    
    return {
        "os": host_os, "arch": host_arch, "compilers": compilers,
        "has_ndk": has_ndk, "has_mingw": has_mingw,
        "has_multilib": has_multilib,
        "current_android_arch": current_android_arch,
    }

def get_recommended_targets(host: Dict) -> Tuple[List[str], List[int]]:
    host_os = host["os"]
    host_arch = host["arch"]
    possible = []
    recommended = []
    
    def add(target: str, is_recommended: bool):
        if target not in possible:
            possible.append(target)
            if is_recommended:
                recommended.append(len(possible) - 1)
    
    if host_os == "linux":
        if host_arch == "x86_64":
            add("linux:x86_64", True)
            if host.get("has_multilib"):
                add("linux:x86_32", True)
            else:
                add("linux:x86_32", False)
        elif host_arch == "x86_32":
            add("linux:x86_32", True)
        elif host_arch == "aarch64":
            add("linux:arm64-v8a", True)
        elif host_arch == "arm":
            add("linux:armeabi-v7a", True)
        
        if find_executable("aarch64-linux-gnu-gcc"):
            add("linux:arm64-v8a", True)
        if find_executable("arm-linux-gnueabihf-gcc"):
            add("linux:armeabi-v7a", True)
        
        if host["has_mingw"]:
            add("windows:x86_64", True)
            add("windows:x86_32", True)
        if host["has_ndk"]:
            for t in ["android:arm64-v8a", "android:armeabi-v7a", "android:x86_64"]:
                add(t, True)
        for t in ALL_TARGETS:
            if t not in possible: add(t, False)
            
    elif host_os == "windows":
        if host_arch == "x86_64": add("windows:x86_64", True)
        elif host_arch == "x86_32": add("windows:x86_32", True)
        if host["has_ndk"]:
            for t in ["android:arm64-v8a", "android:armeabi-v7a", "android:x86_64"]: add(t, True)
        for t in ALL_TARGETS:
            if t not in possible: add(t, False)
            
    elif host_os == "android":
        if host["current_android_arch"]: add(f"android:{host['current_android_arch']}", True)
        if host["has_ndk"]:
            for t in ["android:arm64-v8a", "android:armeabi-v7a", "android:x86_64"]:
                if t not in possible: add(t, True)
        for t in ALL_TARGETS:
            if t not in possible: add(t, False)
    else:
        if host["has_ndk"]:
            for t in ["android:arm64-v8a", "android:armeabi-v7a", "android:x86_64"]: add(t, True)
        for t in ALL_TARGETS:
            if t not in possible: add(t, False)
    
    return possible, recommended

def select_compiler(host: Dict) -> Tuple[str, str, str]:
    """Returns (compiler_name, c_compiler_path, cxx_compiler_path)"""
    compilers = host["compilers"]
    if not compilers:
        log_error("No C/C++ compiler found (need clang or gcc in PATH)")
        sys.exit(1)
    if len(compilers) == 1:
        name, cc, cxx = compilers[0]
        log_info(f"Using compiler: {name}")
        return name, cc, cxx
    
    options = [f"{name} ({cc})" for name, cc, _ in compilers]
    default_idx = 0 if compilers[0][0] == "clang" else 1
    idx = interactive_choice("Select compiler:", options, default_idx)
    name, cc, cxx = compilers[idx]
    log_info(f"Using compiler: {name}")
    return name, cc, cxx

# ============================================================================
# Submodule Management
# ============================================================================

def ensure_git_submodules():
    log_step("🔍 Checking git submodules")
    for rel_path in ALL_SUBMODULES:
        target = ROOT_DIR / rel_path
        if not target.exists() or not any(target.iterdir()):
            log_info(f"Initializing {rel_path}...")
            if not run_cmd(["git", "submodule", "update", "--init", str(target)]):
                log_warn(f"Could not initialize {rel_path} via git.")
    log_success("Git submodules are ready")

def copy_header_libs():
    log_info("Copying header-only libraries...")
    GLOBAL_INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    
    stb_dir = ROOT_DIR / "vendor/include/stb"
    if stb_dir.is_dir() and any(stb_dir.iterdir()):
        for f in stb_dir.rglob("*.h"):
            rel = f.relative_to(stb_dir)
            dst = GLOBAL_INCLUDE_DIR / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, dst)
        log_success("Copied STB headers")
    else:
        log_warn("STB directory not found or empty, skipping")

# ============================================================================
# Toolchain Configuration
# ============================================================================

def build_toolchain_config(platform: str, arch: str, host: Dict, compiler_name: str, cc: str, cxx: str) -> Optional[Dict]:
    cfg: Dict = {"is_native": False}
    host_os = host["os"]
    host_arch = host["arch"]

        if platform == "linux":
        is_native = (
            (arch == "x86_64" and host_arch == "x86_64") or
            (arch == "x86_32" and host_arch in ("x86_32", "x86_64")) or
            (arch == "arm64-v8a" and host_arch == "aarch64") or
            (arch == "armeabi-v7a" and host_arch == "arm")
        )
        if is_native and host_os == "linux":
            cfg["is_native"] = True
            cfg["c_compiler"] = cc
            if arch == "x86_32" and host_arch == "x86_64":
                cfg["c_flags"] = "-m32"
                cfg["ld_flags"] = "-m32"
        else:
            if host_os != "linux":
                log_warn(f"Cannot cross-compile Linux {arch} from {host_os}")
                return None
            
            # Compiler mapping
            prefix_map = {
                "arm64-v8a": "aarch64-linux-gnu", 
                "armeabi-v7a": "arm-linux-gnueabihf",
            }
            
            # Target mapping for clang --target
            clang_target_map = {
                "arm64-v8a": "aarch64-linux-gnu",
                "armeabi-v7a": "arm-linux-gnueabihf",
            }
            
            prefix = prefix_map.get(arch)
            if not prefix: 
                log_warn(f"No cross-compiler mapping for Linux {arch}")
                return None
            
            # Try 1: GCC prefix compiler
            gcc = find_executable(f"{prefix}-gcc")
            if gcc:
                cfg["system_name"] = "Linux"
                cfg["c_compiler"] = f"{prefix}-gcc"
                return cfg
            
            # Try 2: Clang with --target (needs GCC toolchain for sysroot)
            clang = find_executable("clang")
            if clang and host.get("compilers") and any(c[0] == "clang" for c in host["compilers"]):
                # Check if GCC toolchain exists (provides sysroot + binutils)
                gcc_toolchain = find_executable(f"{prefix}-gcc")
                if gcc_toolchain or find_executable(f"{prefix}-ld"):
                    target = clang_target_map.get(arch)
                    cfg["system_name"] = "Linux"
                    cfg["c_compiler"] = "clang"
                    cfg["c_flags"] = f"--target={target}"
                    cfg["ld_flags"] = f"--target={target}"
                    log_info(f"Using clang with --target={target} (GCC toolchain for sysroot)")
                    return cfg
            
            log_warn(f"Cross-compiler for Linux {arch} not found (tried {prefix}-gcc and clang --target)")
            return None
        return cfg

    elif platform == "windows":
        # Use clang or gcc based on user selection
        if compiler_name == "clang":
            prefix = "x86_64-w64-mingw32-clang" if arch == "x86_64" else "i686-w64-mingw32-clang"
            alt_prefix = "x86_64-w64-mingw32-gcc" if arch == "x86_64" else "i686-w64-mingw32-gcc"
        else:
            prefix = "x86_64-w64-mingw32-gcc" if arch == "x86_64" else "i686-w64-mingw32-gcc"
            alt_prefix = "x86_64-w64-mingw32-clang" if arch == "x86_64" else "i686-w64-mingw32-clang"
        
        gcc = find_executable(prefix)
        if not gcc:
            # Try alternative
            gcc = find_executable(alt_prefix)
            if gcc:
                prefix = alt_prefix
        
        if not gcc:
            if host_os == "windows" and arch == ("x86_64" if host_arch == "x86_64" else "x86_32"):
                alt = find_executable("gcc")
                if alt and "mingw" in str(alt).lower(): gcc = alt
            if not gcc:
                log_warn(f"MinGW {prefix} not found, skipping Windows {arch}")
                return None
        
        cfg.update({
            "system_name": "Windows", 
            "c_compiler": prefix,
            "rc_compiler": prefix.replace("-gcc", "-windres").replace("-clang", "-windres"),
        })
        return cfg

    elif platform == "android":
        if host_os == "android" and arch == host["current_android_arch"]:
            cfg["is_native"] = True
            cfg["c_compiler"] = cc
            target_map = {
                "arm64-v8a": f"aarch64-linux-android{ANDROID_MIN_SDK}",
                "armeabi-v7a": f"armv7a-linux-androideabi{ANDROID_MIN_SDK}",
                "x86_64": f"x86_64-linux-android{ANDROID_MIN_SDK}",
            }
            if arch in target_map:
                cfg["c_flags"] = f"-target {target_map[arch]}"
            return cfg
        
        if not host["has_ndk"]: return None
        
        ndk_path = None
        ndk_candidates = [
            os.environ.get("ANDROID_NDK"), os.environ.get("ANDROID_NDK_HOME"),
            str(Path.home() / "Android/Sdk/ndk-bundle"),
        ]
        for search_dir in [
            Path.home() / "Android/Sdk/ndk", Path.home() / "Library/Android/sdk/ndk",
            Path.home() / "AppData/Local/Android/Sdk/ndk",
        ]:
            if search_dir.is_dir():
                ndk_candidates += [str(d) for d in search_dir.iterdir() if d.is_dir()]
        for p in ndk_candidates:
            if p and Path(p).is_dir() and (Path(p) / "build/cmake/android.toolchain.cmake").exists():
                ndk_path = p
                break
        if not ndk_path: return None
        
        abi_map = {
            "arm64-v8a": "arm64-v8a", 
            "armeabi-v7a": "armeabi-v7a",
            "x86_64": "x86_64",
            "x86_32": "x86",
        }
        android_abi = abi_map.get(arch, arch)
        
        cfg.update({
            "toolchain_file": str(Path(ndk_path) / "build/cmake/android.toolchain.cmake"),
            "android_abi": android_abi,
            "android_platform": f"android-{ANDROID_MIN_SDK}",
            "android_stl": "c++_static",
        })
        return cfg

    return None

# ============================================================================
# Build Logic
# ============================================================================

def setup_build_dirs(platform: str, arch: str) -> Tuple[Path, Path]:
    install_dir = VENDOR_DIR / arch / platform
    build_dir = VENDOR_DIR / "build" / arch / platform
    if build_dir.exists():
        try: safe_rmtree(build_dir)
        except Exception as e:
            log_error(f"Failed to clean build dir: {e}")
            sys.exit(1)
    build_dir.mkdir(parents=True, exist_ok=True)
    install_dir.mkdir(parents=True, exist_ok=True)
    GLOBAL_INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    return install_dir, build_dir

def collect_headers(install_dir: Path):
    inc_dir = install_dir / "include"
    if inc_dir.is_dir():
        for root, _, files in os.walk(inc_dir):
            for f in files:
                src = Path(root) / f
                rel = src.relative_to(inc_dir)
                dst = GLOBAL_INCLUDE_DIR / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
        log_info(f"Headers merged into {GLOBAL_INCLUDE_DIR}")

def run_cmake_build(lib_name: str, src_dir: Path, install_dir: Path, build_dir: Path,
                     toolchain: Dict, extra_cmake_flags: List[str]) -> bool:
    if toolchain.get("toolchain_file"):
        label = f"Android-{toolchain.get('android_abi', '?')}"
    elif toolchain.get("is_native"):
        label = f"Native-{sys_platform.machine()}"
    else:
        label = f"{toolchain.get('system_name', '?')}-cross"
    
    log_step(f"🔨 [{label}] Building {lib_name}")

    cmake_args = [
        "cmake", "-B", str(build_dir), "-S", str(src_dir),
        "-DCMAKE_BUILD_TYPE=Release", "-DBUILD_SHARED_LIBS=OFF",
        "-DCMAKE_POSITION_INDEPENDENT_CODE=ON", f"-DCMAKE_INSTALL_PREFIX={install_dir}",
    ]

    if toolchain.get("toolchain_file"):
        cmake_args.append(f"-DCMAKE_TOOLCHAIN_FILE={toolchain['toolchain_file']}")
        if toolchain.get("android_abi"): cmake_args.append(f"-DANDROID_ABI={toolchain['android_abi']}")
        if toolchain.get("android_platform"): cmake_args.append(f"-DANDROID_PLATFORM={toolchain['android_platform']}")
        if toolchain.get("android_stl"): cmake_args.append(f"-DANDROID_STL={toolchain['android_stl']}")
    else:
        if toolchain.get("system_name"): cmake_args.append(f"-DCMAKE_SYSTEM_NAME={toolchain['system_name']}")
        if toolchain.get("c_compiler"): cmake_args.append(f"-DCMAKE_C_COMPILER={toolchain['c_compiler']}")
        if toolchain.get("rc_compiler"): cmake_args.append(f"-DCMAKE_RC_COMPILER={toolchain['rc_compiler']}")
        if toolchain.get("c_flags"): cmake_args.append(f"-DCMAKE_C_FLAGS={toolchain['c_flags']}")
        if toolchain.get("ld_flags"): cmake_args.append(f"-DCMAKE_EXE_LINKER_FLAGS={toolchain['ld_flags']}")

    cmake_args.extend(extra_cmake_flags)

    if not run_cmd(cmake_args):
        log_error(f"Configure failed for {lib_name}")
        return False

    parallel_jobs = max(1, os.cpu_count() or 4)
    build_cmd = ["cmake", "--build", str(build_dir), "--target", "install", "--parallel", str(parallel_jobs)]
    if not run_cmd(build_cmd):
        log_error(f"Build failed for {lib_name}")
        return False

    collect_headers(install_dir)
    log_success(f"{lib_name} installed to {install_dir}")
    return True

def build_glfw(toolchain: Dict, install_dir: Path, build_dir: Path) -> bool:
    src = ROOT_DIR / "vendor/src/glfw"
    if not (src / "CMakeLists.txt").exists(): return True
    
    flags = [
        "-DGLFW_BUILD_EXAMPLES=OFF", 
        "-DGLFW_BUILD_TESTS=OFF",
        "-DGLFW_BUILD_DOCS=OFF",
    ]
    
    if toolchain.get("android_abi") or (toolchain.get("system_name") == "Linux" and not toolchain.get("is_native", True)):
        flags.extend([
            "-DGLFW_BUILD_X11=OFF",
            "-DGLFW_BUILD_WAYLAND=OFF",
        ])
        
    return run_cmake_build("glfw", src, install_dir, build_dir, toolchain, flags)

def build_freetype(toolchain: Dict, install_dir: Path, build_dir: Path) -> bool:
    src = ROOT_DIR / "vendor/src/freetype"
    if not (src / "CMakeLists.txt").exists(): return True
    
    flags = [
        "-DFT_DISABLE_ZLIB=ON", "-DFT_DISABLE_BZIP2=ON",
        "-DFT_DISABLE_PNG=ON", "-DFT_DISABLE_HARFBUZZ=ON", "-DFT_DISABLE_BROTLI=ON",
    ]
    return run_cmake_build("freetype", src, install_dir, build_dir, toolchain, flags)

# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description="Build Rinegine vendor submodules")
    parser.add_argument("--target", help="Build only one target (e.g., linux:x86_64)")
    parser.add_argument("--all", action="store_true", help="Build all possible targets (no prompts)")
    parser.add_argument("--list-targets", action="store_true", help="List targets and exit")
    parser.add_argument("--detect-host", action="store_true", help="Show host capabilities and exit")
    args = parser.parse_args()

    host = detect_host()
    
    if args.detect_host:
        print(f"Host OS:       {host['os']}")
        print(f"Host Arch:     {host['arch']}")
        print(f"Compilers:     {[c[0] for c in host['compilers']]}")
        print(f"Multilib (-m32): {host.get('has_multilib', False)}")
        print(f"NDK available: {host['has_ndk']}")
        print(f"MinGW available: {host['has_mingw']}")
        print(f"Current Android arch: {host['current_android_arch']}")
        return 0

    possible_targets, recommended_indices = get_recommended_targets(host)
    
    if args.list_targets:
        print("Possible targets for this host:")
        for i, t in enumerate(possible_targets):
            marker = "★" if i in recommended_indices else " "
            print(f"  {marker} {t}")
        print("\n★ = recommended (dependencies available)")
        return 0

    if args.target:
        if args.target not in ALL_TARGETS:
            log_error(f"Unknown target: {args.target}")
            return 1
        targets_to_build = [args.target]
        log_info(f"Building single target: {args.target}")
    elif args.all:
        targets_to_build = possible_targets
        log_info(f"Building all {len(targets_to_build)} possible targets")
    else:
        log_step("🎯 Target Selection")
        print(f"\nDetected host: {host['os']} / {host['arch']}")
        print(f"Recommended targets are marked with ★")
        print(f"({len(recommended_indices)} of {len(possible_targets)} have all dependencies installed)\n")
        selected_indices = interactive_multi_select("Select targets to build:", possible_targets, recommended_indices)
        targets_to_build = [possible_targets[i] for i in selected_indices]
        log_info(f"Selected {len(targets_to_build)} target(s)")

    log_step("🔧 Compiler Selection")
    compiler_name, cc, cxx = select_compiler(host)

    log_step("🚀 Preparation")
    ensure_git_submodules()
    copy_header_libs()

    log_step("🎯 Phase 1: Building GLFW")
    glfw_failures = []
    for target_spec in targets_to_build:
        platform, arch = target_spec.split(":")
        install_dir, build_dir = setup_build_dirs(platform, arch)
        tc = build_toolchain_config(platform, arch, host, compiler_name, cc, cxx)
        if not tc:
            log_warn(f"Skipping {target_spec}: toolchain not available on this host")
            continue
        if not build_glfw(tc, install_dir, build_dir):
            log_warn(f"GLFW failed for {target_spec}")
            glfw_failures.append(target_spec)

    log_step("🎯 Phase 2: Building FreeType")
    ft_failures = []
    for target_spec in targets_to_build:
        platform, arch = target_spec.split(":")
        install_dir, build_dir = setup_build_dirs(platform, arch)
        tc = build_toolchain_config(platform, arch, host, compiler_name, cc, cxx)
        if not tc: continue
        if not build_freetype(tc, install_dir, build_dir):
            log_warn(f"FreeType failed for {target_spec}")
            ft_failures.append(target_spec)

    log_step("🎉 Build Complete")
    print(f"  📁 Headers:   {GLOBAL_INCLUDE_DIR}")
    print(f"  📁 Libraries: {VENDOR_DIR}/{{arch}}/{{platform}}/lib/")
    
    if glfw_failures or ft_failures:
        print("\n  ⚠️  Failed targets:")
        for t in glfw_failures: print(f"      GLFW:      {t}")
        for t in ft_failures: print(f"      FreeType:  {t}")
    
    print("\n  💡 Linking examples:")
    print(f"    Linux (OpenGL + Vulkan):")
    print(f"      -I{GLOBAL_INCLUDE_DIR} -L{VENDOR_DIR}/x86_64/linux/lib -lglfw3 -lfreetype -lGL -lvulkan -lpthread -ldl")
    print(f"    Windows (OpenGL + Vulkan + DirectX):")
    print(f"      -I{GLOBAL_INCLUDE_DIR} -L{VENDOR_DIR}/x86_64/windows/lib -lglfw3 -lfreetype -lopengl32 -lvulkan-1 -lgdi32 -ld3d11 -ldxgi")
    print(f"    Android (OpenGL ES + Vulkan):")
    print(f"      -I{GLOBAL_INCLUDE_DIR} -L{VENDOR_DIR}/arm64-v8a/android/lib -lglfw3 -lfreetype -lGLESv2 -lEGL -lvulkan -landroid -llog")
    print(f"  💡 Add 'vendor/build/' to .gitignore")
    
    return 1 if (glfw_failures or ft_failures) else 0

if __name__ == "__main__":
    sys.exit(main())