#!/usr/bin/env python3
# ================== #
"""
The script was generated by AI and may not work correctly.
I'll add this functionality to the builder later; this is a temporary solution.
"""
# ================== #
# -*- coding: utf-8 -*-
"""
Universal vendor submodule initializer & builder for Rinegine.
Smart host-aware build with interactive target/compiler selection.
Usage: python3 vendor/build_vendor.py [--target platform:arch] [--all]
"""

import os
import sys
import subprocess
import shutil
import argparse
import time
from pathlib import Path
from typing import Optional, Tuple, List, Dict
import platform as sys_platform

# ============================================================================
# Configuration
# ============================================================================

try:
    ROOT_DIR = Path(
        subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
    )
except FileNotFoundError:
    print("❌ Error: git is not installed or not in PATH")
    sys.exit(1)
except subprocess.CalledProcessError:
    print("❌ Error: Not inside a Git repository.")
    sys.exit(1)

VENDOR_DIR = ROOT_DIR / "vendor"
GLOBAL_INCLUDE_DIR = VENDOR_DIR / "include"
ANDROID_MIN_SDK = 21

GIT_SUBMODULES = {
    "vendor/src/glfw": "CMakeLists.txt",
    "vendor/src/freetype": "CMakeLists.txt",
}

HEADER_LIBS = {
    "vendor/include/stb": "stb_image.h",
}

ALL_TARGETS = [
    "linux:x86-64", "linux:x86-32", "linux:arm64-v8a", "linux:armeabi-v7a",
    "windows:x86-64", "windows:x86-32",
    "android:arm64-v8a", "android:armeabi-v7a", "android:x86-64",
]

# ============================================================================
# Utility Functions
# ============================================================================

def log_step(msg: str):
    print(f"\n{'='*65}\n {msg}\n{'='*65}")

def log_info(msg: str):
    print(f"  ℹ️  {msg}")

def log_success(msg: str):
    print(f"  ✅ {msg}")

def log_warn(msg: str):
    print(f"  ⚠️  {msg}")

def log_error(msg: str):
    print(f"  ❌ {msg}", file=sys.stderr)

def find_executable(name: str) -> Optional[Path]:
    path = shutil.which(name)
    return Path(path) if path else None

def ask_path(prompt: str, default: Optional[str] = None) -> str:
    if default:
        val = input(f"{prompt} [{default}]: ").strip()
        return val or default
    return input(f"{prompt}: ").strip()

def run_cmd(cmd: List[str], cwd: Optional[Path] = None) -> bool:
    log_info(f"$ {' '.join(str(c) for c in cmd)}")
    try:
        subprocess.run(cmd, cwd=cwd, check=True)
        return True
    except subprocess.CalledProcessError:
        return False
    except FileNotFoundError:
        log_error(f"Command not found: {cmd[0]}")
        return False

def safe_rmtree(path: Path, retries: int = 3):
    if not path.exists():
        return
    for attempt in range(retries):
        try:
            shutil.rmtree(path)
            return
        except PermissionError:
            if attempt < retries - 1:
                log_warn(f"File locked, retrying... ({attempt + 1}/{retries})")
                time.sleep(1)
            else:
                log_error(f"Cannot remove {path}: files are locked")
                raise

def interactive_choice(prompt: str, options: List[str], default: int = 0) -> int:
    """Show numbered menu and return selected index (0-based)."""
    print(f"\n{prompt}")
    for i, opt in enumerate(options):
        marker = "➤" if i == default else " "
        print(f"  {marker} [{i+1}] {opt}")
    while True:
        choice = input(f"\nEnter number [1-{len(options)}] (default={default+1}): ").strip()
        if not choice:
            return default
        try:
            idx = int(choice) - 1
            if 0 <= idx < len(options):
                return idx
        except ValueError:
            pass
        print("Invalid input, try again.")

def interactive_multi_select(prompt: str, options: List[str], recommended: List[int]) -> List[int]:
    """Allow user to select multiple options. Returns list of selected indices."""
    print(f"\n{prompt}")
    print("  (Enter comma-separated numbers, 'r' for recommended, 'a' for all, or 'q' to confirm)")
    for i, opt in enumerate(options):
        marker = "★" if i in recommended else " "
        print(f"  {marker} [{i+1}] {opt}")
    
    while True:
        choice = input(f"\nYour choice (default='r'): ").strip().lower()
        if not choice or choice == "r":
            return recommended
        if choice == "a":
            return list(range(len(options)))
        if choice == "q":
            return recommended
        try:
            selected = [int(x.strip()) - 1 for x in choice.split(",")]
            if all(0 <= i < len(options) for i in selected):
                return selected
        except ValueError:
            pass
        print("Invalid input, try again.")

# ============================================================================
# Host Capability Detection
# ============================================================================

def detect_host() -> Dict:
    """Detect host OS, architecture, and available toolchains."""
    host_os = sys_platform.system().lower()
    host_arch = sys_platform.machine().lower()
    
    # Normalize host arch
    if host_arch in ("amd64", "x86_64"):
        host_arch = "x86_64"
    elif host_arch in ("i686", "i386", "x86"):
        host_arch = "x86"
    elif "aarch64" in host_arch or "arm64" in host_arch:
        host_arch = "aarch64"
    elif "arm" in host_arch:
        host_arch = "arm"
    
    # Detect available compilers
    compilers = []
    if find_executable("clang") and find_executable("clang++"):
        compilers.append(("clang", str(find_executable("clang")), str(find_executable("clang++"))))
    if find_executable("gcc") and find_executable("g++"):
        compilers.append(("gcc", str(find_executable("gcc")), str(find_executable("g++"))))
    
    # Check NDK
    has_ndk = False
    ndk_candidates = [
        os.environ.get("ANDROID_NDK"),
        os.environ.get("ANDROID_NDK_HOME"),
        str(Path.home() / "Android/Sdk/ndk-bundle"),
        str(Path.home() / "AppData/Local/Android/Sdk/ndk-bundle"),
    ]
    if host_os == "darwin":
        ndk_candidates.append(str(Path.home() / "Library/Android/sdk/ndk-bundle"))
    for search_dir in [
        Path.home() / "Android/Sdk/ndk",
        Path.home() / "Library/Android/sdk/ndk",
        Path.home() / "AppData/Local/Android/Sdk/ndk",
    ]:
        if search_dir.is_dir():
            ndk_candidates += [str(d) for d in search_dir.iterdir() if d.is_dir()]
    
    for p in ndk_candidates:
        if p and Path(p).is_dir() and (Path(p) / "build/cmake/android.toolchain.cmake").exists():
            has_ndk = True
            break
    
    # Check MinGW
    has_mingw = bool(find_executable("x86_64-w64-mingw32-gcc") or find_executable("i686-w64-mingw32-gcc"))
    
    # Check Linux cross-compilers
    has_linux_cross = bool(
        find_executable("aarch64-linux-gnu-gcc") or 
        find_executable("arm-linux-gnueabihf-gcc") or
        find_executable("i686-linux-gnu-gcc")
    )
    
    # Determine current Android arch (for Termux)
    if host_arch == "aarch64":
        current_android_arch = "arm64-v8a"
    elif host_arch == "arm":
        current_android_arch = "armeabi-v7a"
    else:
        current_android_arch = None
    
    return {
        "os": host_os,
        "arch": host_arch,
        "compilers": compilers,
        "has_ndk": has_ndk,
        "has_mingw": has_mingw,
        "has_linux_cross": has_linux_cross,
        "current_android_arch": current_android_arch,
    }

def get_recommended_targets(host: Dict) -> Tuple[List[str], List[int]]:
    """Return (all_possible_targets, recommended_indices)."""
    host_os = host["os"]
    host_arch = host["arch"]
    
    possible = []
    recommended = []
    
    # Helper to add target
    def add(target: str, is_recommended: bool):
        if target not in possible:
            possible.append(target)
            if is_recommended:
                recommended.append(len(possible) - 1)
    
    if host_os == "linux":
        # Native Linux
        if host_arch == "x86_64":
            add("linux:x86-64", True)
        elif host_arch == "x86":
            add("linux:x86-32", True)
        elif host_arch == "aarch64":
            add("linux:arm64-v8a", True)
        elif host_arch == "arm":
            add("linux:armeabi-v7a", True)
        
        # Cross-compiled Linux
        if host["has_linux_cross"]:
            for t in ["linux:arm64-v8a", "linux:armeabi-v7a", "linux:x86-32"]:
                add(t, True)
        
        # Windows via MinGW
        if host["has_mingw"]:
            add("windows:x86-64", True)
            add("windows:x86-32", True)
        
        # Android via NDK
        if host["has_ndk"]:
            for t in ["android:arm64-v8a", "android:armeabi-v7a", "android:x86-64"]:
                add(t, True)
        
        # Add all as non-recommended fallbacks
        for t in ALL_TARGETS:
            if t not in possible:
                add(t, False)
    
    elif host_os == "windows":
        # Native Windows
        if host_arch == "x86_64":
            add("windows:x86-64", True)
        elif host_arch == "x86":
            add("windows:x86-32", True)
        
        # Android via NDK
        if host["has_ndk"]:
            for t in ["android:arm64-v8a", "android:armeabi-v7a", "android:x86-64"]:
                add(t, True)
        
        # Fallbacks (likely won't work but allow manual selection)
        for t in ALL_TARGETS:
            if t not in possible:
                add(t, False)
    
    elif host_os == "android":
        # Termux: only current Android arch via system clang
        if host["current_android_arch"]:
            add(f"android:{host['current_android_arch']}", True)
        
        # NDK allows cross-Android archs
        if host["has_ndk"]:
            for t in ["android:arm64-v8a", "android:armeabi-v7a", "android:x86-64"]:
                if t not in possible:
                    add(t, True)
        
        # Fallbacks
        for t in ALL_TARGETS:
            if t not in possible:
                add(t, False)
    
    else:  # darwin, freebsd, etc.
        if host["has_ndk"]:
            for t in ["android:arm64-v8a", "android:armeabi-v7a", "android:x86-64"]:
                add(t, True)
        for t in ALL_TARGETS:
            if t not in possible:
                add(t, False)
    
    return possible, recommended

def select_compiler(host: Dict) -> Tuple[str, str]:
    """Let user choose compiler if multiple are available."""
    compilers = host["compilers"]
    if not compilers:
        log_error("No C/C++ compiler found (need clang or gcc in PATH)")
        sys.exit(1)
    
    if len(compilers) == 1:
        name, cc, cxx = compilers[0]
        log_info(f"Using compiler: {name}")
        return cc, cxx
    
    # Multiple compilers: ask user
    options = [f"{name} ({cc})" for name, cc, _ in compilers]
    # Prefer clang
    default_idx = 0 if compilers[0][0] == "clang" else 1
    idx = interactive_choice("Select compiler:", options, default_idx)
    _, cc, cxx = compilers[idx]
    log_info(f"Using compiler: {compilers[idx][0]}")
    return cc, cxx

# ============================================================================
# Submodule Management
# ============================================================================

def ensure_git_submodules():
    log_step("🔍 Checking git submodules")
    for rel_path, marker in GIT_SUBMODULES.items():
        target = ROOT_DIR / rel_path
        if not (target / marker).exists():
            log_info(f"Initializing {rel_path}...")
            if not run_cmd(["git", "submodule", "update", "--init", str(target)]):
                log_error(f"Failed to initialize {rel_path}")
                sys.exit(1)
    log_success("Git submodules are ready")

def copy_header_libs():
    log_info("Copying header-only libraries...")
    GLOBAL_INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    
    for rel_path, marker in HEADER_LIBS.items():
        src_dir = ROOT_DIR / rel_path
        if not src_dir.is_dir() or not (src_dir / marker).exists():
            log_warn(f"{rel_path} missing {marker}, skipping")
            continue
        
        for f in src_dir.glob("*.h"):
            shutil.copy2(f, GLOBAL_INCLUDE_DIR / f.name)
        log_success(f"Copied headers from {rel_path}")

# ============================================================================
# Toolchain Configuration
# ============================================================================

def build_toolchain_config(platform: str, arch: str, host: Dict, cc: str, cxx: str) -> Optional[Dict]:
    """Build CMake toolchain configuration dict."""
    cfg: Dict = {"is_native": False}
    host_os = host["os"]
    host_arch = host["arch"]

    # --- Linux ---
    if platform == "linux":
        # Check if this is a native build
        is_native = (
            (arch == "x86-64" and host_arch == "x86_64") or
            (arch == "x86-32" and host_arch == "x86") or
            (arch == "arm64-v8a" and host_arch == "aarch64") or
            (arch == "armeabi-v7a" and host_arch == "arm")
        )
        
        if is_native and host_os == "linux":
            cfg["is_native"] = True
            cfg["c_compiler"] = cc
            cfg["cxx_compiler"] = cxx
            # x86-32 on x86_64 host needs -m32
            if arch == "x86-32" and host_arch == "x86_64":
                cfg["c_flags"] = "-m32"
                cfg["cxx_flags"] = "-m32"
        else:
            # Cross-compilation from Linux
            if host_os != "linux":
                log_warn(f"Cannot cross-compile Linux {arch} from {host_os}")
                return None
            
            prefix_map = {
                "arm64-v8a": "aarch64-linux-gnu",
                "armeabi-v7a": "arm-linux-gnueabihf",
                "x86-32": "i686-linux-gnu",
            }
            prefix = prefix_map.get(arch)
            if not prefix:
                log_warn(f"No cross-compiler mapping for Linux {arch}")
                return None
            
            gcc = find_executable(f"{prefix}-gcc")
            if not gcc:
                log_warn(f"Cross-compiler {prefix}-gcc not found, skipping Linux {arch}")
                return None
            
            cfg["system_name"] = "Linux"
            cfg["c_compiler"] = f"{prefix}-gcc"
            cfg["cxx_compiler"] = f"{prefix}-g++"
        return cfg

    # --- Windows (MinGW only — produces .a) ---
    elif platform == "windows":
        prefix = "x86_64-w64-mingw32" if arch == "x86-64" else "i686-w64-mingw32"
        gcc = find_executable(f"{prefix}-gcc")
        
        if not gcc:
            if host_os == "windows" and arch == ("x86-64" if host_arch == "x86_64" else "x86-32"):
                # Native Windows: try MinGW anyway (user said we want .a everywhere)
                alt = find_executable("gcc")
                if alt and "mingw" in str(alt).lower():
                    gcc = alt
            
            if not gcc:
                log_warn(f"MinGW {prefix}-gcc not found, skipping Windows {arch}")
                return None
        
        cfg.update({
            "system_name": "Windows",
            "c_compiler": f"{prefix}-gcc",
            "cxx_compiler": f"{prefix}-g++",
            "rc_compiler": f"{prefix}-windres",
        })
        return cfg

    # --- Android ---
    elif platform == "android":
        # Case 1: Termux (host_os == "android") — use system clang for current arch
        if host_os == "android" and arch == host["current_android_arch"]:
            cfg["is_native"] = True
            cfg["c_compiler"] = cc
            cfg["cxx_compiler"] = cxx
            # Android system clang needs target flag
            target_map = {
                "arm64-v8a": f"aarch64-linux-android{ANDROID_MIN_SDK}",
                "armeabi-v7a": f"armv7a-linux-androideabi{ANDROID_MIN_SDK}",
                "x86-64": f"x86_64-linux-android{ANDROID_MIN_SDK}",
            }
            cfg["c_flags"] = f"-target {target_map[arch]}"
            cfg["cxx_flags"] = f"-target {target_map[arch]}"
            return cfg
        
        # Case 2: Any host with NDK
        if not host["has_ndk"]:
            log_warn("NDK not found, cannot build Android")
            return None
        
        # Find NDK path
        ndk_path = None
        ndk_candidates = [
            os.environ.get("ANDROID_NDK"),
            os.environ.get("ANDROID_NDK_HOME"),
            str(Path.home() / "Android/Sdk/ndk-bundle"),
        ]
        for search_dir in [
            Path.home() / "Android/Sdk/ndk",
            Path.home() / "Library/Android/sdk/ndk",
            Path.home() / "AppData/Local/Android/Sdk/ndk",
        ]:
            if search_dir.is_dir():
                ndk_candidates += [str(d) for d in search_dir.iterdir() if d.is_dir()]
        
        for p in ndk_candidates:
            if p and Path(p).is_dir() and (Path(p) / "build/cmake/android.toolchain.cmake").exists():
                ndk_path = p
                break
        
        if not ndk_path:
            log_warn("NDK path not found despite has_ndk=True")
            return None
        
        cfg.update({
            "toolchain_file": str(Path(ndk_path) / "build/cmake/android.toolchain.cmake"),
            "android_abi": arch,
            "android_platform": f"android-{ANDROID_MIN_SDK}",
            "android_stl": "c++_static",
        })
        return cfg

    return None

# ============================================================================
# Build Logic
# ============================================================================

def setup_build_dirs(platform: str, arch: str) -> Tuple[Path, Path]:
    install_dir = VENDOR_DIR / arch / platform
    build_dir = VENDOR_DIR / "build" / arch / platform
    
    if build_dir.exists():
        try:
            safe_rmtree(build_dir)
        except Exception as e:
            log_error(f"Failed to clean build dir: {e}")
            sys.exit(1)
    
    build_dir.mkdir(parents=True, exist_ok=True)
    install_dir.mkdir(parents=True, exist_ok=True)
    GLOBAL_INCLUDE_DIR.mkdir(parents=True, exist_ok=True)
    return install_dir, build_dir

def collect_headers(install_dir: Path):
    inc_dir = install_dir / "include"
    if inc_dir.is_dir():
        for root, _, files in os.walk(inc_dir):
            for f in files:
                src = Path(root) / f
                rel = src.relative_to(inc_dir)
                dst = GLOBAL_INCLUDE_DIR / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
        log_info(f"Headers merged into {GLOBAL_INCLUDE_DIR}")

def run_cmake_build(lib_name: str, src_dir: Path, install_dir: Path, build_dir: Path,
                     toolchain: Dict, extra_cmake_flags: List[str]) -> bool:
    # Build label
    if toolchain.get("toolchain_file"):
        label = f"Android-{toolchain.get('android_abi', '?')}"
    elif toolchain.get("is_native"):
        label = f"Native-{sys_platform.machine()}"
    else:
        label = f"{toolchain.get('system_name', '?')}-cross"
    
    log_step(f"🔨 [{label}] Building {lib_name}")

    cmake_args = [
        "cmake", "-B", str(build_dir), "-S", str(src_dir),
        "-DCMAKE_BUILD_TYPE=Release",
        "-DBUILD_SHARED_LIBS=OFF",
        "-DCMAKE_POSITION_INDEPENDENT_CODE=ON",
        f"-DCMAKE_INSTALL_PREFIX={install_dir}",
    ]

    if toolchain.get("toolchain_file"):
        cmake_args.append(f"-DCMAKE_TOOLCHAIN_FILE={toolchain['toolchain_file']}")
        if toolchain.get("android_abi"):
            cmake_args.append(f"-DANDROID_ABI={toolchain['android_abi']}")
        if toolchain.get("android_platform"):
            cmake_args.append(f"-DANDROID_PLATFORM={toolchain['android_platform']}")
        if toolchain.get("android_stl"):
            cmake_args.append(f"-DANDROID_STL={toolchain['android_stl']}")
    else:
        if toolchain.get("system_name"):
            cmake_args.append(f"-DCMAKE_SYSTEM_NAME={toolchain['system_name']}")
        if toolchain.get("c_compiler"):
            cmake_args.append(f"-DCMAKE_C_COMPILER={toolchain['c_compiler']}")
        if toolchain.get("cxx_compiler"):
            cmake_args.append(f"-DCMAKE_CXX_COMPILER={toolchain['cxx_compiler']}")
        if toolchain.get("rc_compiler"):
            cmake_args.append(f"-DCMAKE_RC_COMPILER={toolchain['rc_compiler']}")
        if toolchain.get("c_flags"):
            cmake_args.append(f"-DCMAKE_C_FLAGS={toolchain['c_flags']}")
        if toolchain.get("cxx_flags"):
            cmake_args.append(f"-DCMAKE_CXX_FLAGS={toolchain['cxx_flags']}")

    cmake_args.extend(extra_cmake_flags)

    if not run_cmd(cmake_args):
        log_error(f"Configure failed for {lib_name}")
        return False

    parallel_jobs = max(1, os.cpu_count() or 4)
    build_cmd = ["cmake", "--build", str(build_dir), "--target", "install", "--parallel", str(parallel_jobs)]
    if not run_cmd(build_cmd):
        log_error(f"Build failed for {lib_name}")
        return False

    collect_headers(install_dir)
    log_success(f"{lib_name} installed to {install_dir}")
    return True

def build_glfw(toolchain: Dict, install_dir: Path, build_dir: Path) -> bool:
    glfw_rel = next((k for k in GIT_SUBMODULES if "glfw" in k), None)
    if not glfw_rel:
        return True
    src = ROOT_DIR / glfw_rel
    if not (src / "CMakeLists.txt").exists():
        return True
    
    flags = [
        "-DGLFW_BUILD_EXAMPLES=OFF", "-DGLFW_BUILD_TESTS=OFF",
        "-DGLFW_BUILD_DOCS=OFF", "-DGLFW_VULKAN_STATIC=OFF",
    ]
    return run_cmake_build("glfw", src, install_dir, build_dir, toolchain, flags)

def build_freetype(toolchain: Dict, install_dir: Path, build_dir: Path) -> bool:
    ft_rel = next((k for k in GIT_SUBMODULES if "freetype" in k), None)
    if not ft_rel:
        return True
    src = ROOT_DIR / ft_rel
    if not (src / "CMakeLists.txt").exists():
        return True
    
    flags = [
        "-DFT_DISABLE_ZLIB=ON", "-DFT_DISABLE_BZIP2=ON",
        "-DFT_DISABLE_PNG=ON", "-DFT_DISABLE_HARFBUZZ=ON", "-DFT_DISABLE_BROTLI=ON",
    ]
    return run_cmake_build("freetype", src, install_dir, build_dir, toolchain, flags)

# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description="Build Rinegine vendor submodules")
    parser.add_argument("--target", help="Build only one target (e.g., linux:x86-64)")
    parser.add_argument("--all", action="store_true", help="Build all possible targets (no prompts)")
    parser.add_argument("--list-targets", action="store_true", help="List targets and exit")
    parser.add_argument("--detect-host", action="store_true", help="Show host capabilities and exit")
    args = parser.parse_args()

    # Detect host environment
    host = detect_host()
    
    if args.detect_host:
        print(f"Host OS:       {host['os']}")
        print(f"Host Arch:     {host['arch']}")
        print(f"Compilers:     {[c[0] for c in host['compilers']]}")
        print(f"NDK available: {host['has_ndk']}")
        print(f"MinGW available: {host['has_mingw']}")
        print(f"Linux cross-compilers: {host['has_linux_cross']}")
        print(f"Current Android arch: {host['current_android_arch']}")
        return 0

    possible_targets, recommended_indices = get_recommended_targets(host)
    
    if args.list_targets:
        print("Possible targets for this host:")
        for i, t in enumerate(possible_targets):
            marker = "★" if i in recommended_indices else " "
            print(f"  {marker} {t}")
        print("\n★ = recommended (dependencies available)")
        return 0

    # Determine which targets to build
    if args.target:
        if args.target not in ALL_TARGETS:
            log_error(f"Unknown target: {args.target}")
            return 1
        targets_to_build = [args.target]
        log_info(f"Building single target: {args.target}")
    elif args.all:
        targets_to_build = possible_targets
        log_info(f"Building all {len(targets_to_build)} possible targets")
    else:
        # Interactive selection
        log_step("🎯 Target Selection")
        print(f"\nDetected host: {host['os']} / {host['arch']}")
        print(f"Recommended targets are marked with ★")
        print(f"({len(recommended_indices)} of {len(possible_targets)} have all dependencies installed)\n")
        
        selected_indices = interactive_multi_select(
            "Select targets to build:",
            possible_targets,
            recommended_indices
        )
        targets_to_build = [possible_targets[i] for i in selected_indices]
        log_info(f"Selected {len(targets_to_build)} target(s)")

    # Compiler selection (once for all targets)
    log_step("🔧 Compiler Selection")
    cc, cxx = select_compiler(host)

    # Prepare submodules
    log_step("🚀 Preparation")
    ensure_git_submodules()
    copy_header_libs()

    # Phase 1: GLFW for all selected targets
    log_step("🎯 Phase 1: Building GLFW")
    glfw_failures = []
    for target_spec in targets_to_build:
        platform, arch = target_spec.split(":")
        install_dir, build_dir = setup_build_dirs(platform, arch)
        tc = build_toolchain_config(platform, arch, host, cc, cxx)
        if not tc:
            log_warn(f"Skipping {target_spec}: toolchain not available on this host")
            continue
        if not build_glfw(tc, install_dir, build_dir):
            log_warn(f"GLFW failed for {target_spec}")
            glfw_failures.append(target_spec)

    # Phase 2: FreeType for all selected targets
    log_step("🎯 Phase 2: Building FreeType")
    ft_failures = []
    for target_spec in targets_to_build:
        platform, arch = target_spec.split(":")
        install_dir, build_dir = setup_build_dirs(platform, arch)
        tc = build_toolchain_config(platform, arch, host, cc, cxx)
        if not tc:
            continue
        if not build_freetype(tc, install_dir, build_dir):
            log_warn(f"FreeType failed for {target_spec}")
            ft_failures.append(target_spec)

    # Summary
    log_step("🎉 Build Complete")
    print(f"  📁 Headers:   {GLOBAL_INCLUDE_DIR}")
    print(f"  📁 Libraries: {VENDOR_DIR}/{{arch}}/{{platform}}/lib/")
    
    if glfw_failures or ft_failures:
        print("\n  ⚠️  Failed targets:")
        for t in glfw_failures:
            print(f"      GLFW:      {t}")
        for t in ft_failures:
            print(f"      FreeType:  {t}")
    
    print("\n  💡 Linking example:")
    print(f"    -I{GLOBAL_INCLUDE_DIR}")
    print(f"    -L{VENDOR_DIR}/x86-64/linux/lib -lglfw3 -lfreetype")
    print(f"  💡 Add 'vendor/build/' to .gitignore")
    
    return 1 if (glfw_failures or ft_failures) else 0

if __name__ == "__main__":
    sys.exit(main())