#pragma once

#include "V2/set.hpp"
#include "impl.hpp"
#include "util.hpp"
#include "types.hpp"
#include "stream.hpp"
#include "iostream.hpp"
#include "fstream.hpp"
// #include "include.hpp"
// #include "concept.hpp"
// // #include "WIP.h"
// #include "impl.hpp"
// #include "util.hpp"
// #include "types.hpp"
// #include "pull_allocator.hpp"
// #include "allocator.hpp"
// #include "stream.hpp"
// #include "iostream.hpp"
// #include "fstream.hpp"